spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:rec/bili.db

#mybatis-plus:
#  configuration:
#    # 日志输出到控制台
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888